---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

# Setup environment
```{r}
#install.packages("tidyverse")
#install.packages("gridExtra")
library(tidyverse)
library(gridExtra)
alcDataOrig <- read_csv("data/HappinessAlcoholRegulations-2016.csv")
```

```{r}
alcData <- alcDataOrig %>%
  mutate(OnPremisePurchaseAge = parse_number(OnPremisePurchaseAge))

# Remove NA values
rowsBefore <- nrow(alcData)
alcData <- alcData[!is.na(alcData$OnPremisePurchaseAge), ]
rowsAfter <- nrow(alcData)
sprintf("%d/%d rows removed", rowsBefore - rowsAfter, rowsBefore, rowsAfter)

alcData
```

# Plots

```{r}
ageVsFreedom <- alcData %>%
  ggplot(aes(x = `OnPremisePurchaseAge`, 
             y = `Freedom`)) +
  geom_point(alpha = .5) +
  geom_smooth(method = "lm")

ageVsHapp <- alcData %>%
  ggplot(aes(x = `OnPremisePurchaseAge`, 
             y = `HappinessScore`)) +
  geom_point(alpha = .5) +
  geom_smooth(method = "lm")

grid.arrange(ageVsFreedom, ageVsHapp, ncol=2)
```

```{r}
beerVsHapp <- alcData %>%
  ggplot(aes(x = `Beer_PerCapita`, 
             y = `HappinessScore`)) +
  geom_point(alpha = .5) +
  geom_smooth(method = "lm")

wineVsHapp <- alcData %>%
  ggplot(aes(x = `Wine_PerCapita`, 
             y = `HappinessScore`)) +
  geom_point(alpha = .5) +
  geom_smooth(method = "lm")

spiritVsHapp <- alcData %>%
  ggplot(aes(x = `Spirit_PerCapita`, 
             y = `HappinessScore`)) +
  geom_point(alpha = .5) +
  geom_smooth(method = "lm")

grid.arrange(beerVsHapp, wineVsHapp, spiritVsHapp, ncol=2)
```

```{r}
beerVsFree <- alcData %>%
  ggplot(aes(x = `Beer_PerCapita`, 
             y = `Freedom`)) +
  geom_point(alpha = .5) +
  geom_smooth(method = "lm") +
  xlab("Beer Per Capita") +
  ylab("Freedom Score")

wineVsFree <- alcData %>%
  ggplot(aes(x = `Wine_PerCapita`, 
             y = `Freedom`)) +
  geom_point(alpha = .5) +
  geom_smooth(method = "lm") +
  xlab("Wine Per Capita") +
  ylab("Freedom Score") 

spiritVsFree <- alcData %>%
  ggplot(aes(x = `Spirit_PerCapita`, 
             y = `Freedom`)) +
  geom_point(alpha = .5) +
  geom_smooth(method = "lm") +
  xlab("Spirit Per Capita") +
  ylab("Freedom Score") 

grid.arrange(beerVsFree, wineVsFree, spiritVsFree, ncol=2, top="How Alcohol Consumption Relates to Feelings of Freedom")
```

```{r}
alcData %>%
  ggplot(aes(x = `HappinessScore`, 
             y = `Freedom`)) +
  geom_point(alpha = .5) +
  geom_smooth(method = "lm") +
  xlab("Happiness Score") +
  ylab("Freedom Score") +
  labs(title = "How Feelings of Freedom Relate to Happiness Score of a Country")
```

```{r}
alcData <- alcData %>% mutate(totalAlc = (Spirit_PerCapita + Wine_PerCapita + Beer_PerCapita))

alcData %>%
  ggplot(aes(x = `HappinessScore`, 
             y = `totalAlc`)) +
  geom_point(alpha = .5) +
  geom_smooth(method = "lm") +
facet_wrap(~Region) +
  xlab("Happiness Score") +
  ylab("Alcohol Consumption Per Capita") +
  labs(title = "How Alcohol Consumption Relates to Happiness Score by Region", 
       subtitle = "Happiness Score was created based on a scaled happiness survey") 
```

```{r}
byRegion <- alcData %>% mutate(total = (Spirit_PerCapita + Wine_PerCapita + Beer_PerCapita))

a <- byRegion %>% filter(Region == "Australia and New Zealand") %>% group_by(OnPremisePurchaseAge) %>% summarise(mean = mean(total))
a <- a %>%
  ggplot(aes(x = `OnPremisePurchaseAge`, 
             y = mean)) +
  geom_col(fill = "blue3") +
  scale_x_continuous(breaks=c(15,16,17,18,19,20,21)) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1),axis.title.x=element_blank(), axis.title.y=element_blank(), plot.title = element_text(size=10, hjust = 0.5)) +  ylim(0, 700) +
  labs(title = "Australia and \nNew Zealand")

ce <- byRegion %>% filter(Region == "Central and Eastern Europe") %>% group_by(OnPremisePurchaseAge) %>% summarise(mean = mean(total))
ce <- ce %>%
  ggplot(aes(x = `OnPremisePurchaseAge`, 
             y = mean)) +
  geom_col(fill = "blue3") +
  scale_x_continuous(breaks=c(18,20)) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1),axis.title.x=element_blank(), axis.title.y=element_blank(), plot.title = element_text(size=10, hjust = 0.5)) +  ylim(0, 700) +
  labs(title = "Central and \nEastern Europe")

ea <- byRegion %>% filter(Region == "Eastern Asia") %>% group_by(OnPremisePurchaseAge) %>% summarise(mean = mean(total))
ea <- ea %>%
  ggplot(aes(x = `OnPremisePurchaseAge`, 
             y = mean)) +
  geom_col(fill = "blue3") +
  scale_x_continuous(breaks=c(15,16,17,18,19,20,21)) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1),axis.title.x=element_blank(), axis.title.y=element_blank(), plot.title = element_text(size=10, hjust = 0.5)) +  ylim(0, 700) +
  labs(title = "Eastern Asia")

la <- byRegion %>% filter(Region == "Latin America and Caribbean") %>% group_by(OnPremisePurchaseAge) %>% summarise(mean = mean(total))
la <- la %>%
  ggplot(aes(x = `OnPremisePurchaseAge`, 
             y = mean)) +
  geom_col(fill = "blue3") +
  scale_x_continuous(breaks=c(16,18,20)) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1),axis.title.x=element_blank(), axis.title.y=element_blank(), plot.title = element_text(size=10, hjust = 0.5)) +  ylim(0, 700) +
  labs(title = "Latin America and \nCaribbean")

me <- byRegion %>% filter(Region == "Middle East and Northern Africa") %>% group_by(OnPremisePurchaseAge) %>% summarise(mean = mean(total))
me <- me %>%
  ggplot(aes(x = `OnPremisePurchaseAge`, 
             y = mean)) +
  geom_col(fill = "blue3") +
  scale_x_continuous(breaks=c(16,18)) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1),axis.title.x=element_blank(), axis.title.y=element_blank(), plot.title = element_text(size=10, hjust = 0.5)) +  ylim(0, 700) +
  labs(title = "Middle East and \nNorthern Africa")

na <- byRegion %>% filter(Region == "North America") %>% group_by(OnPremisePurchaseAge) %>% summarise(mean = mean(total))
na <- na %>%
  ggplot(aes(x = `OnPremisePurchaseAge`, 
             y = mean)) +
  geom_col(fill = "blue3") +
  scale_x_continuous(breaks=c(18,21)) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1),axis.title.x=element_blank(), axis.title.y=element_blank(), plot.title = element_text(size=10, hjust = 0.5)) +  ylim(0, 700) +
  labs(title = "North America")

sea <- byRegion %>% filter(Region == "Southeastern Asia") %>% group_by(OnPremisePurchaseAge) %>% summarise(mean = mean(total))
sea <- sea %>%
  ggplot(aes(x = `OnPremisePurchaseAge`, 
             y = mean)) +
  geom_col(fill = "blue3") +
  scale_x_continuous(breaks=c(18,20)) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1),axis.title.x=element_blank(), axis.title.y=element_blank(), plot.title = element_text(size=10, hjust = 0.5)) +  ylim(0, 700) +
  labs(title = "SouthEastern Asia")

sa <- byRegion %>% filter(Region == "Sub-Saharan Africa") %>% group_by(OnPremisePurchaseAge) %>% summarise(mean = mean(total))
sa <- sa %>%
  ggplot(aes(x = `OnPremisePurchaseAge`, 
             y = mean)) +
  geom_col(fill = "blue3") +
  scale_x_continuous(breaks=c(15,16,17,18,19,20,21)) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1),axis.title.x=element_blank(), axis.title.y=element_blank(), plot.title = element_text(size=10, hjust = 0.5)) +  ylim(0, 700) +
  labs(title = "Sub-Saharan Africa")

we <- byRegion %>% filter(Region == "Western Europe") %>% group_by(OnPremisePurchaseAge) %>% summarise(mean = mean(total))
we <- we %>%
  ggplot(aes(x = `OnPremisePurchaseAge`, 
             y = mean)) +
  geom_col(fill = "blue3") +
  scale_x_continuous(breaks=c(15,16,17,18,19,20,21)) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1),axis.title.x=element_blank(), axis.title.y=element_blank(), plot.title = element_text(size=10, hjust = 0.5)) +
  ylim(0, 700) +
  labs(title = "Western Europe")

grid.arrange(a, ce, ea, la, me, na, sea, sa, we, ncol=3, top="How Alcohol Consumption Relates to Legal Drinking Age by Region",
             bottom="Legal Drinking Age", 
               left="Alcohol Consumption Per Capita")
```

```{r}
alcData <- alcData %>% arrange(alcData$HappinessRank)
top <- alcData %>% head(5)
bottom <- alcData %>% tail(5)
alc<- full_join(top,bottom)
alc <- alc %>% mutate(total = (Spirit_PerCapita + Wine_PerCapita + Beer_PerCapita))
alc %>%
  ggplot(aes(x = factor(Country,c('Denmark', 'Switzerland', 'Iceland', 'Norway', 'Finland', 'Chad', 'Madagascar', 'Tanzania', 'Liberia', 'Syria')), 
             y = `total`, fill = GDP_PerCapita)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  xlab("Top 5 and Bottom 5 Happiness Scoring Countries (Left to Right)") +
  ylab("Alcohol Consumption Per Capita") +
  labs(title = "How Alcohol Consumption and GDP Relates to Happiness Scores by Country", fill='GDP Per Capita')
```

```{r}
alcData <- alcData %>% arrange(alcData$HappinessRank)
top <- alcData %>% head(5)
bottom <- alcData %>% tail(5)
alc<- full_join(top,bottom)
alc <- alc %>% mutate(total = (Spirit_PerCapita + Wine_PerCapita + Beer_PerCapita))
plot <- alc %>%
  ggplot(aes(x = factor(Country,c('Denmark', 'Switzerland', 'Iceland', 'Norway', 'Finland', 'Chad', 'Madagascar', 'Tanzania', 'Liberia', 'Syria')), 
             y = `total`, fill = factor(OnPremisePurchaseAge))) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  xlab("Top 5 and Bottom 5 Happiness Scoring Countries (Left to Right)") +
  ylab("Alcohol Consumption Per Capita") +
  labs(title = "How Alcohol Consumption Relates and \nLegal Drinking Age to Happiness Scores by Country", fill='Legal Drinking Age')
plot + scale_fill_brewer(palette="Blues")
```

# Compare countries with and without age restrictions
```{r}
alcDataNoAge <- alcDataOrig %>%
  filter(OnPremisePurchaseAge == "No age minimum")

meanWithAge <- mean(alcData$HappinessScore)
minWithAge <- min(alcData$HappinessScore)
maxWithAge <- max(alcData$HappinessScore)

meanNoAge <- mean(alcDataNoAge$HappinessScore)
minNoAge <- min(alcDataNoAge$HappinessScore)
maxNoAge <- max(alcDataNoAge$HappinessScore)

stat <- c(meanWithAge, meanNoAge, minWithAge, minNoAge, maxWithAge, maxNoAge)
stat_type <- c("mean", "mean", "min", "min", "max", "max")
stat_label <- c("Age Restrictions", "No Age Restrictions", "Age Restrictions", "No Age Restrictions", "Age Restrictions", "No Age Restrictions")
withWithoutAge <- data.frame(stat, stat_type, stat_label)

withWithoutAge %>%
  ggplot(aes(x = stat_label,
             y = stat,
             fill = factor(stat_label))) +
  geom_col() +
  facet_wrap(~stat_type) +
  xlab("Summary Statistics") +
  ylab("Happiness Score") +
  labs(title = "How Happiness Differs In Countries\nWith and Without Drinking Age Restrictions", fill='Drinking Restrictions') +
  theme(axis.ticks.x = element_blank(),
        axis.text.x = element_blank()) +
  scale_fill_brewer(palette = "Paired")
```

```{r}
alcDataNoAge <- alcDataNoAge %>%
  mutate(TotalAlc_PerCapita = Beer_PerCapita + Wine_PerCapita + Spirit_PerCapita)

alcData <- alcData %>%
  mutate(TotalAlc_PerCapita = Beer_PerCapita + Wine_PerCapita + Spirit_PerCapita)

meanWithAge <- mean(alcData$TotalAlc_PerCapita)
minWithAge <- min(alcData$TotalAlc_PerCapita)
maxWithAge <- max(alcData$TotalAlc_PerCapita)

meanNoAge <- mean(alcDataNoAge$TotalAlc_PerCapita)
minNoAge <- min(alcDataNoAge$TotalAlc_PerCapita)
maxNoAge <- max(alcDataNoAge$TotalAlc_PerCapita)

stat <- c(meanWithAge, meanNoAge, minWithAge, minNoAge, maxWithAge, maxNoAge)
stat_type <- c("mean", "mean", "min", "min", "max", "max")
stat_label <- c("Age Restrictions", "No Age Restrictions", "Age Restrictions", "No Age Restrictions", "Age Restrictions", "No Age Restrictions")
consWithWithoutAge <- data.frame(stat, stat_type, stat_label)

consWithWithoutAge %>%
  ggplot(aes(x = stat_label,
             y = stat,
             fill = factor(stat_label))) +
  geom_col() +
  facet_wrap(~stat_type) +
  xlab("") +
  ylab("Average Alcohol Consumption") +
  labs(title = "Average Alcohol Consumption in Countries\nWith and Without Drinking Age Restrictions", fill='Drinking Restrictions') +
  theme(axis.ticks.x = element_blank(),
        axis.text.x = element_blank()) +
  scale_fill_brewer(palette = "Paired")
```

